### ISSUE TITLE
vcovHC.ivreg non-exported?

### ISSUE THREAD

**Issue by tappek** [john-d-fox/ivreg#11]
Seems like vcovHC.ivreg is not registered/exported in ivreg_0.6-1:

```
> ivreg::vcovHC(m)
Error: 'vcovHC' is not an exported object from 'namespace:ivreg'
> ivreg:::vcovHC.ivreg() # does exist
```

**Comment by zeileis** [comment]
That is correct. `vcovHC()` is a generic function provided by the `sandwich` package. Its method for `ivreg` objects is registered when the `sandwich` namespace is loaded.

```
example(ivreg)
sandwich::vcovHC(m)
##              (Intercept) log(rprice) log(rincome)
## (Intercept)    1.8328931  -0.4963656    0.2048129
## log(rprice)   -0.4963656   0.1625447   -0.1049835
## log(rincome)   0.2048129  -0.1049835    0.1101652
```

**Comment by tappek** [comment]
Ah, this was intentionally!
We do it the other way round in `plm` and _import_ the generic from `sandwich` (and, thus, `sandwich` is a hard dependency), so users can just `vcovHC(<plm_object>)`.
