### ISSUE TITLE
three-part right side

### ISSUE THREAD

**Issue by MarcoKuehne** [john-d-fox/ivreg#14]
https://cran.r-project.org/web/packages/ivreg/vignettes/ivreg.html says _As listing exogenous variables in both parts on the right-hand side of the formula may become tedious if there are many of them, an additional convenience option is to use a three-part right side like y ~ x1 | x2 | z1 + z2, listing the exogenous, endogenous, and instrumental variables (for the endogenous variables only), respectively._

This does not work for me. 

```
# data
data("SchoolingReturns")

# ivreg basic
library(ivreg)

ivreg(log(packs) ~ log(rprice) + log(rincome) | salestax + log(rincome), data = CigaretteDemand)
ivreg(log(packs) ~ log(rprice) | log(rincome) | salestax, data = CigaretteDemand)
```

**Comment by zeileis** [comment]
Note that `log(rincome)` is the exogenous variable because it is an instrument for itself in the two-part specification. Thus, `log(rprice)` is the endogenous variable that is instrumented through `salestestax`. The corresponding three-part formula is

```
ivreg(log(packs) ~ log(rincome) | log(rprice) | salestax, data = CigaretteDemand)
```

**Comment by MarcoKuehne** [comment]
Hi @zeileis Thanks for your response. The code returns:

```
Error in ivreg(log(packs) ~ log(rincome) | log(rprice) | salestax, data = CigaretteDemand) : 
  length(formula)[2] %in% 1:2 ist nicht TRUE
```

for me.

**Comment by zeileis** [comment]
Maybe you are not using the most recent version `ivreg`? You need at least version 0.6-0, the current CRAN release is:

```
packageVersion("ivreg")
## [1] '0.6.1'
```

**Comment by MarcoKuehne** [comment]
Issue was on my end. I had several other iv packages loaded. AER was among them and masked `ivreg`.
