### ISSUE TITLE
Complete vcov for aliased models

### ISSUE THREAD

**Issue by zeileis** [john-d-fox/ivreg#2]
As pointed out in the discussion of https://github.com/john-d-fox/ivreg/issues/1 the `vcov()` method for `ivreg` objects _always_ drops the rows/columns pertaining to aliased coeffcients while the `lm` method retains them by default. In contrast, the `coef()` method _always_ retains the aliased coefficients. It would be good to be more consistent with `lm` here. A simple non-sensical example is provided below.

With `lm`:
```
library("ivreg")
data("cars", package = "datasets")
cars$const <- 1
m <- lm(dist ~ speed + const, data = cars)
coef(m)
## (Intercept)       speed       const 
##  -17.579095    3.932409          NA 
 coef(m, complete = FALSE)
## (Intercept)       speed 
##  -17.579095    3.932409 
vcov(m)
##             (Intercept)      speed const
## (Intercept)   45.676514 -2.6588234    NA
## speed         -2.658823  0.1726509    NA
## const                NA         NA    NA
vcov(m, complete = FALSE)
##             (Intercept)      speed
## (Intercept)   45.676514 -2.6588234
## speed         -2.658823  0.1726509
```
Versus `ivreg`:
```
iv <- ivreg(dist ~ speed + const | log(speed) + const, data = cars)
coef(iv)
## (Intercept)       speed       const 
##   -15.36537     3.78866          NA 
vcov(iv)
##             (Intercept)      speed
## (Intercept)   48.985379 -2.8729188
## speed         -2.872919  0.1865532

```

**Comment by zeileis** [comment]
Thanks for the updates in: https://github.com/john-d-fox/ivreg/commit/9152d085c73167c799903e83b93f1feac56d5767#diff-9fbd246d3f21e979c161727778abc0c3

While `complete = TRUE`/`FALSE` seems to work as intended for the stage-1 results, `complete = TRUE` appears to be ignored in the `vcov()` for the default stage-2 results.

**Comment by john-d-fox** [comment]
Hi again,

This bug is now fixed.

John

**Comment by zeileis** [comment]
Thanks, looks good to me, closing the issue now.
