### ISSUE TITLE
Three-part right-hand side

### ISSUE THREAD

**Issue by zeileis** [john-d-fox/ivreg#3]
Currently, `ivreg()` requires a two-part right-hand side in the formula corresponding to the X and Z matrices in 2SLS, respectively:

    y ~ ex + en | ex + in

where `ex` corresponds to all _exogenous_ and `en` to all _endogenous_ and `in` to all _instrument_ variables.

However, this notation can be a bit cumbersome if we have many exogenous variables and just one endogenous variable and one corresponding instrument. This is why the manual page points out that you can do:

    y ~ ex + en | . - en + in

This is a bit technical, though, and in a discussion with @grantmcdermott we thought that it might help to support a three-part right-had side:

    y ~ ex | en | in

It would be really hard to fully support that in the sense that terms etc. would also need to change. But supporting it in the top-level `ivreg()` function just by converting it to the two-part case requires just the following additional code:

    if(length(formula)[2] == 3L) formula <- as.Formula(
      formula(formula, rhs = c(1, 2), collapse = TRUE),
      formula(formula, lhs = 0, rhs = c(1, 3), collapse = TRUE)
    )

This would have to be inserted between line 141 and 142 of `ivreg.R`. For example, it would turn

    formula <- Formula(y ~ x1 | x2 + x3 | z1 + z2)

into

    y ~ x1 + (x2 + x3) | x1 + (z1 + z2)

My feeling is that the three-part right-hand side in the intput would be easier for some users. I'm just not sure whether it would create more confusion for some users as well.

Thoughts?

**Comment by john-d-fox** [comment]
Hi,
On 2020-12-07 6:05 p.m., Achim Zeileis wrote:
> Currently, |ivreg()| requires a two-part right-hand side in the formula 
> corresponding to the X and Z matrices in 2SLS, respectively:
> 
> |y ~ ex + en | ex + in |
> 
> where |ex| corresponds to all /exogenous/ and |en| to all /endogenous/ 
> and |in| to all /instrument/ variables.
> 
> However, this notation can be a bit cumbersome if we have many exogenous 
> variables and just one endogenous variable and one corresponding 
> instrument. This is why the manual page points out that you can do:
> 
> |y ~ ex + en | . - en + in |
> 
> This is a bit technical, though, and in a discussion with 
> @grantmcdermott <https://github.com/grantmcdermott> we thought that it 
> might help to support a three-part right-had side:
> 
> |y ~ ex | en | in |
> 
> It would be really hard to fully support that in the sense that terms 
> etc. would also need to change. But supporting it in the top-level 
> |ivreg()| function just by converting it to the two-part case requires 
> just the following additional code:
> 
> |if(length(formula)[2] == 3L) formula <- as.Formula( formula(formula, 
> rhs = c(1, 2), collapse = TRUE), formula(formula, lhs = 0, rhs = c(1, 
> 3), collapse = TRUE) ) |
> 
> This would have to be inserted between line 141 and 142 of |ivreg.R|. 
> For example, it would turn
> 
> |formula <- Formula(y ~ x1 | x2 + x3 | z1 + z2) |
> 
> into
> 
> |y ~ x1 + (x2 + x3) | x1 + (z1 + z2) |
> 
> My feeling is that the three-part right-hand side in the intput would be 
> easier for some users. I'm just not sure whether it would create more 
> confusion for some users as well
> 
> Thoughts?

I like this idea. People who don't want to use the three-part 
specification can ignore it. It shouldn't be hard to write clear 
documentation explaining the various options, both in the .Rd file for 
ivreg() and in the vigentte.

Best,
John

**Comment by zeileis** [comment]
Thanks for the feedback, done now. I also updated the manual page and included a short note in the "Getting started" vignette.

_Question:_ When converting the three parts to two parts, should we use `y ~ ex + en | en + in` or `y ~ en + ex | en + in`, i.e., always list endogenous variables first? I guess that there are more applications where the endogenous variable is the one of main interest.

**Comment by john-d-fox** [comment]
Hi,

On 2020-12-07 9:35 p.m., Achim Zeileis wrote:
> Thanks for the feedback, done now. I also updated the manual page and 
> included a short note in the "Getting started" vignette.
> 
> /Question:/ When converting the three parts to two parts, should we use 
> |y ~ ex + en | en + in| or |y ~ en + ex | en + in|, i.e., always list 

Don't you mean y ~ ex + en | ex + in (i.e., y = endogenous response; en 
= endogenous regressors; ex = exogenous regressors) and y ~ en + ex | ex 
+ in?

> endogenous variables first? I guess that there are more applications 
> where the endogenous variable is the one of main interest.

Yes, I'd put the endogenous regressor(s) first (and of course there may 
be more than one). Also, I'm sorry to be pedantic but I find it useful 
to consistently distinguish between explanatory variables and regressors 
and it's really the latter that the formula implies.

Best,
  John

**Comment by zeileis** [comment]
Yes, sorry for the confusion! Maybe it would be even better to use `y ~ en | in | ex` and map that to `y ~ en + ex | in + ex`? This would also facilitate `y ~ en | in | .` with `.` when there are a lot of exogenous variables.

Re: explanatory variable vs. regressor. I'm not sure which usage you would prefer here, could you explain? I'm usually using regressors to refer to columns in a regressor matrix.

**Comment by john-d-fox** [comment]
I'm sorry that I wasn't clear about explanatory variables vs. regressors. 

In a schematic formula like `y ~ en + ex | in + ex`, `y`, `en`, `ex`, and `in` aren't really either variables or regressors. `y` is an expression that generates the response variable (e.g., it could be `log(y)`), while `en`, etc., are elements of the RHS of the formula that generate terms and regressors (e.g., `en` could be `poly(x1, 2)*x2 + log(x3)`). This makes it hard to talk about a schematic formula like `y ~ en + ex | in + ex`, so maybe it's OK as a short hand to refer to `y` as the response, `en` as the endogenous explanatory variables, etc. I wish there were a less awkward way to formulate all this.

I think that `y ~ en | ex | in` makes more sense because both `en` and `ex` are explanatory variables (in the short-hand sense), while `ex` and `in` are both exogenous (i.e., independent of the errors) and thus instrumental variables -- that is, `ex` are exogenous explanatory variables and `in` are exogenous variables that don't appear as explanatory variables.

**Comment by zeileis** [comment]
@john-d-fox I've left this issue open, because I accidentally made the commits in the wrong branch (in "robust" rather than "main"). But code and documentation are really finished and would be ready for release. @grantmcdermott mentioned that he would be interested in using the three-part formula in teaching.

How do you feel about merging "robust" into "main" and making a new release? The robust part wouldn't have to be advertised much or could be flagged as "still under development" maybe?

**Comment by john-d-fox** [comment]
Hi Achim,

On 2021-01-30 2:34 p.m., Achim Zeileis wrote:
> @john-d-fox <https://github.com/john-d-fox> I've left this issue open, 
> because I accidentally made the commits in the wrong branch (in "robust" 
> rather than "main"). But code and documentation are really finished and 
> would be ready for release. @grantmcdermott 
> <https://github.com/grantmcdermott> mentioned that he would be 
> interested in using the three-part formula in teaching.
> 
> How do you feel about merging "robust" into "main" and making a new 
> release? The robust part wouldn't have to be advertised much or could be 
> flagged as "still under development" maybe?

I was going to suggest much the same thing -- that is, merging the 
branches, not necessarily releasing a new version -- but I don't see a 
reason not to release the current development version. Is there more to 
do on robust estimation?

Best,
  John

**Comment by zeileis** [comment]
To me the robust stuff looked good but I also did only some light testing. It should be good enough for release, I think.

Before advertising it it would probably be good to do some simulations regarding the level of robustness attained by this approach.

**Comment by john-d-fox** [comment]
Hi,

On 2021-01-30 3:06 p.m., Achim Zeileis wrote:
> To me the robust stuff looked good but I also did only some light 
> testing. It should be good enough for release, I think.
> 
> Before advertising it it would probably be good to do some simulations 
> regarding the level of robustness attained by this approach.

Sure, that makes sense. More generally, we should probably write a paper 
about the package, since both the diagnostics and the robust estimator 
are reasonably novel.

I'm working on another project at the moment which will probably last a 
couple of months. I should have some time after that, but I expect that 
your schedule will continue to be pretty full.

Best,
  John

**Comment by john-d-fox** [comment]
I merged the robust branch into main. I guess that we can delete the robust branch now, but I didn't do that in case I misunderstand how this is supposed to work in Git.

**Comment by zeileis** [comment]
Thanks, John! I googled a bit and it seems that the usual recommendation is to delete branches after merging because they remain in the history anyway. The easiest way is to use the web-based GUI to delete the branches. So I think you can do that and then close this issue.
