### ISSUE TITLE
Possible extra #' in helpfile

### ISSUE THREAD

**Issue by remlapmot** [john-d-fox/ivreg#6]
Thanks for the great package.

On line 91 of the ivreg.R file [here](https://github.com/john-d-fox/ivreg/blob/25fb34b4b7dd6dca517109d45b4eee901ab1bfb2/R/ivreg.R#L91) I think you have an extra `#' ` at the beginning of the line.

**Comment by zeileis** [comment]
Thanks for the report, much appreciated. This was fixed by John in https://github.com/john-d-fox/ivreg/commit/dd1df411b7fc93876e2039d70075632c2ef1627c but not reported/closed here, yet.
