### ISSUE TITLE
No `instruments` when omitting intercepts

### ISSUE THREAD

**Issue by lukesonnet** [john-d-fox/ivreg#8]
This may be revealing my fundamental misunderstanding of IVs, but if I were to specify a 2SLS using `ivreg` without intercepts in either equation, `ivreg` seems to believe there are no instruments when computing diagnostics (and therefore fails). Is this the expected behavior? If so, can someone explain to me why? If not, can I help fix it?

Thank you!

Here's a reproducible example using the built in `mtcars` dataset.

``` r
library(ivreg)

ivo <- ivreg(mpg ~ 0 + hp | 0 + cyl, data = mtcars)
ivo$instruments
#> named integer(0)
summary(ivo)
#> Error in ivdiag(object, vcov. = vcov.): no endogenous/instrument variables
sessionInfo()
#> R version 4.1.1 Patched (2021-09-01 r80849)
#> Platform: x86_64-apple-darwin17.0 (64-bit)
#> Running under: macOS Catalina 10.15.6
#> 
#> Matrix products: default
#> BLAS:   /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRblas.0.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] ivreg_0.6-0
#> 
#> loaded via a namespace (and not attached):
#>  [1] zip_2.2.0         Rcpp_1.0.7        cellranger_1.1.0  compiler_4.1.1   
#>  [5] pillar_1.6.2      highr_0.9         forcats_0.5.1     tools_4.1.1      
#>  [9] digest_0.6.27     lattice_0.20-44   evaluate_0.14     lifecycle_1.0.0  
#> [13] tibble_3.1.4      pkgconfig_2.0.3   rlang_0.4.11      openxlsx_4.2.4   
#> [17] reprex_2.0.1      cli_3.0.1         rstudioapi_0.13   curl_4.3.2       
#> [21] yaml_2.2.1        haven_2.4.3       xfun_0.25         rio_0.5.27       
#> [25] fastmap_1.1.0     withr_2.4.2       stringr_1.4.0     knitr_1.33       
#> [29] fs_1.5.0          vctrs_0.3.8       hms_1.1.0         grid_4.1.1       
#> [33] lmtest_0.9-38     glue_1.4.2        data.table_1.14.0 fansi_0.5.0      
#> [37] readxl_1.3.1      foreign_0.8-81    rmarkdown_2.10    carData_3.0-4    
#> [41] Formula_1.2-4     car_3.0-11        magrittr_2.0.1    htmltools_0.5.2  
#> [45] ellipsis_0.3.2    MASS_7.3-54       abind_1.4-5       utf8_1.2.2       
#> [49] stringi_1.7.4     crayon_1.4.1      zoo_1.8-9
```

<sup>Created on 2021-09-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by john-d-fox** [comment]
Dear Luke,

No, you don't misunderstand -- something is wrong here. I believe that 
Achim wrote this part of the code, so maybe he can take a look first.

Thanks for the bug report,
  John

John Fox, Professor Emeritus
McMaster University
Hamilton, Ontario, Canada
web: https://socialsciences.mcmaster.ca/jfox/

**Comment by lukesonnet** [comment]
Great, thanks!

I'm sure @zeileis knows this but the line that this traces back to is here: https://github.com/john-d-fox/ivreg/blame/main/R/ivreg.fit.R#L132, added in this commit: https://github.com/john-d-fox/ivreg/commit/efaa332b07adcb6343498e7cb383d63167ab9409

```r
if(!is.null(auxreg)) {
  endo <- which(colMeans(as.matrix(auxreg$residuals^2)) > sqrt(.Machine$double.eps))
  inst <- which(rowMeans(as.matrix(coef(auxreg)^2)[, -endo, drop = FALSE]) < sqrt(.Machine$double.eps))
  exog <- exog[-endo]
} else {
  endo <- inst <- integer()
}
```

**Comment by zeileis** [comment]
Good catch, thanks for the report @lukesonnet this is very much appreciated! I've tried to fix this now in https://github.com/john-d-fox/ivreg/commit/8576e1aea53b6241f24228c5658ab63c550910b2 by catching `NaN` row sums in the coefficients (in addition to numerical zeros). Also, I make sure that the `$endogenous` list element is correctly named. I hope this addresses all the problems. Please let me know if you spot any remaining issues.

**Comment by john-d-fox** [comment]
Achim, thanks for taking care of this. John
